### ISSUE TITLE
R 4.3.1 is not supported in v5.96 on linux-aarch64

### ISSUE THREAD

**Issue by yangxingyu588** [conda-forge/r-quantreg-feedstock#39]
### Comment:

Does r-quantreg v5.96 [support linux-aarch64](https://anaconda.org/conda-forge/r-quantreg)?
what should l do for this?

**Comment by mfansler** [comment]
Looks like arch builds got disabled in this PR: https://github.com/conda-forge/r-quantreg-feedstock/pull/20. We can revisit building them again. Possibly `r-conquer` wasn't migrated at the time. Try sending a PR that undoes what was dropped in the previous commit.

**Comment by yangxingyu588** [comment]
could l re-add r-quantreg in [arch_rebuild.txt](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/arch_rebuild.txt)?

**Comment by mfansler** [comment]
I'm not sure the bot logic, but I don't believe so (could be wrong 🤷). Create a PR for this feedstock directly, adding back the provider entries in the `conda-forge.yml` and rerendering.

**Comment by yangxingyu588** [comment]
Sorry, l don't understand you, What code do you mean to add to this feedstock? Thanks for your reply

**Comment by mfansler** [comment]
Sorry, I was only on my phone earlier, which makes it hard to communicate and link examples. This is what I meant:

https://github.com/conda-forge/r-quantreg-feedstock/pull/40/commits/1e0dc8205007aa37dc320350c77ac192da74bf8f
